"use strict";(self.webpackChunkreference=self.webpackChunkreference||[]).push([[6153],{3905:function(e,t,n){n.d(t,{Zo:function(){return p},kt:function(){return m}});var a=n(7294);function r(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function o(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);t&&(a=a.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,a)}return n}function i(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?o(Object(n),!0).forEach((function(t){r(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):o(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function l(e,t){if(null==e)return{};var n,a,r=function(e,t){if(null==e)return{};var n,a,r={},o=Object.keys(e);for(a=0;a<o.length;a++)n=o[a],t.indexOf(n)>=0||(r[n]=e[n]);return r}(e,t);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);for(a=0;a<o.length;a++)n=o[a],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(r[n]=e[n])}return r}var c=a.createContext({}),s=function(e){var t=a.useContext(c),n=t;return e&&(n="function"==typeof e?e(t):i(i({},t),e)),n},p=function(e){var t=s(e.components);return a.createElement(c.Provider,{value:t},e.children)},u={inlineCode:"code",wrapper:function(e){var t=e.children;return a.createElement(a.Fragment,{},t)}},h=a.forwardRef((function(e,t){var n=e.components,r=e.mdxType,o=e.originalType,c=e.parentName,p=l(e,["components","mdxType","originalType","parentName"]),h=s(n),m=r,d=h["".concat(c,".").concat(m)]||h[m]||u[m]||o;return n?a.createElement(d,i(i({ref:t},p),{},{components:n})):a.createElement(d,i({ref:t},p))}));function m(e,t){var n=arguments,r=t&&t.mdxType;if("string"==typeof e||r){var o=n.length,i=new Array(o);i[0]=h;var l={};for(var c in t)hasOwnProperty.call(t,c)&&(l[c]=t[c]);l.originalType=e,l.mdxType="string"==typeof e?e:r,i[1]=l;for(var s=2;s<o;s++)i[s]=n[s];return a.createElement.apply(null,i)}return a.createElement.apply(null,n)}h.displayName="MDXCreateElement"},5114:function(e,t,n){n.r(t),n.d(t,{frontMatter:function(){return l},contentTitle:function(){return c},metadata:function(){return s},toc:function(){return p},default:function(){return h}});var a=n(7462),r=n(3366),o=(n(7294),n(3905)),i=["components"],l={},c=void 0,s={unversionedId:"Python Course/Python Try, Catch, Finally",id:"Python Course/Python Try, Catch, Finally",isDocsHomePage:!1,title:"Python Try, Catch, Finally",description:"039. Python Try, Catch, Finally",source:"@site/docs/Python Course/039. Python Try, Catch, Finally.md",sourceDirName:"Python Course",slug:"/Python Course/Python Try, Catch, Finally",permalink:"/reference/docs/Python Course/Python Try, Catch, Finally",editUrl:"https://github.com/facebook/docusaurus/edit/main/website/docs/Python Course/039. Python Try, Catch, Finally.md",tags:[],version:"current",sidebarPosition:39,frontMatter:{},sidebar:"tutorialSidebar",previous:{title:"Python Zip File",permalink:"/reference/docs/Python Course/Python Zip File"},next:{title:"Python readline",permalink:"/reference/docs/Python Course/Python readline"}},p=[{value:"Common Examples of Exception:",id:"common-examples-of-exception",children:[]},{value:"Why should you use Exceptions?",id:"why-should-you-use-exceptions",children:[]},{value:"Rules of Exceptions",id:"rules-of-exceptions",children:[]},{value:"Exceptional Handling Mechanism",id:"exceptional-handling-mechanism",children:[]},{value:"The Try Statement",id:"the-try-statement",children:[]},{value:"The catch Statement",id:"the-catch-statement",children:[{value:"Example:",id:"example",children:[]}]},{value:"Finally Block",id:"finally-block",children:[]},{value:"The Raise Statement",id:"the-raise-statement",children:[{value:"Example:",id:"example-1",children:[]}]},{value:"Important Python Errors",id:"important-python-errors",children:[]},{value:"Other Important Python Exceptions",id:"other-important-python-exceptions",children:[]},{value:"Error vs. Exceptions",id:"error-vs-exceptions",children:[]},{value:"Summary",id:"summary",children:[]}],u={toc:p};function h(e){var t=e.components,n=(0,r.Z)(e,i);return(0,o.kt)("wrapper",(0,a.Z)({},u,n,{components:t,mdxType:"MDXLayout"}),(0,o.kt)("ol",{start:39},(0,o.kt)("li",{parentName:"ol"},"Python Try, Catch, Finally")),(0,o.kt)("h1",{id:"what-is-an-exception-in-python"},"What is an Exception in Python?"),(0,o.kt)("p",null,"An exception is an error which happens at the time of execution of a program. However, while running a program, Python generates an exception that should be handled to avoid your program to crash. In Python language, exceptions trigger automatically on errors, or they can be triggered and intercepted by your code."),(0,o.kt)("p",null,"The exception indicates that, although the event can occur, this type of event happens infrequently. When the method is not able to handle the exception, it is thrown to its caller function. Eventually, when an exception is thrown out of the main function, the program is terminated abruptly."),(0,o.kt)("h2",{id:"common-examples-of-exception"},"Common Examples of Exception:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},"Division by Zero"),(0,o.kt)("li",{parentName:"ul"},"Accessing a file which does not exist."),(0,o.kt)("li",{parentName:"ul"},"Addition of two incompatible types"),(0,o.kt)("li",{parentName:"ul"},"Trying to access a nonexistent index of a sequence"),(0,o.kt)("li",{parentName:"ul"},"Removing the table from the disconnected database server."),(0,o.kt)("li",{parentName:"ul"},"ATM withdrawal of more than the available amount")),(0,o.kt)("h2",{id:"why-should-you-use-exceptions"},"Why should you use Exceptions?"),(0,o.kt)("p",null,"Here are the reasons for using exceptions in Python:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},"Exception handling allows you to separate error-handling code from normal code."),(0,o.kt)("li",{parentName:"ul"},"An exception is a Python object which represents an error."),(0,o.kt)("li",{parentName:"ul"},"As with code comments, exceptions helps you to remind yourself of what the program expects."),(0,o.kt)("li",{parentName:"ul"},"It clarifies the code and enhances readability."),(0,o.kt)("li",{parentName:"ul"},"Allows you to stimulate consequences as the error-handling takes place at one place and in one manner."),(0,o.kt)("li",{parentName:"ul"},"An exception is a convenient method for handling error messages."),(0,o.kt)("li",{parentName:"ul"},"In Python, you can raise an exception in the program by using the raise exception method."),(0,o.kt)("li",{parentName:"ul"},"Raising an exception helps you to break the current code execution and returns the exception back to expection until it is handled."),(0,o.kt)("li",{parentName:"ul"},"Processing exceptions for components which can't handle them directly.")),(0,o.kt)("h2",{id:"rules-of-exceptions"},"Rules of Exceptions"),(0,o.kt)("p",null,"Here are some essential rules of Python exception handling:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},"Exceptions must be class objects"),(0,o.kt)("li",{parentName:"ul"},"For class exceptions, you can use try statement with an except clause which mentions a particular class."),(0,o.kt)("li",{parentName:"ul"},"Even if a statement or expression is syntactically correct, it may display an error when an attempt is made to execute it."),(0,o.kt)("li",{parentName:"ul"},"Errors found during execution are called exceptions, and they are not unconditionally fatal.")),(0,o.kt)("h2",{id:"exceptional-handling-mechanism"},"Exceptional Handling Mechanism"),(0,o.kt)("p",null,"Exception handling is managed by the following 5 keywords:"),(0,o.kt)("ol",null,(0,o.kt)("li",{parentName:"ol"},"try"),(0,o.kt)("li",{parentName:"ol"},"catch"),(0,o.kt)("li",{parentName:"ol"},"finally"),(0,o.kt)("li",{parentName:"ol"},"throw")),(0,o.kt)("h2",{id:"the-try-statement"},"The Try Statement"),(0,o.kt)("p",null,"A try statement includes keyword try, followed by a colon (:) and a suite of code in which exceptions may occur. It has one or more clauses."),(0,o.kt)("p",null,"During the execution of the try statement, if no exceptions occurred then, the interpreter ignores the exception handlers for that specific try statement."),(0,o.kt)("p",null,"In case, if any exception occurs in a try suite, the try suite expires and program control transfers to the matching except handler following the try suite."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-python"},"Syntax:\ntry:\nstatement(s)\n")),(0,o.kt)("h2",{id:"the-catch-statement"},"The catch Statement"),(0,o.kt)("p",null,"Catch blocks take one argument at a time, which is the type of exception that it is likely to catch. These arguments may range from a specific type of exception which can be varied to a catch-all category of exceptions."),(0,o.kt)("p",null,"Rules for catch block:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},"You can define a catch block by using the keyword catch"),(0,o.kt)("li",{parentName:"ul"},"Catch Exception parameter is always enclosed in parentheses"),(0,o.kt)("li",{parentName:"ul"},"It always represents the type of exception that catch block handles."),(0,o.kt)("li",{parentName:"ul"},"An exception handling code is written between two {} curly braces."),(0,o.kt)("li",{parentName:"ul"},"You can place multiple catch block within a single try block."),(0,o.kt)("li",{parentName:"ul"},"You can use a catch block only after the try block."),(0,o.kt)("li",{parentName:"ul"},"All the catch block should be ordered from subclass to superclass exception.")),(0,o.kt)("h3",{id:"example"},"Example:"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-python"},'try\n}\ncatch (ArrayIndexOutOfBoundsException e) {\nSystem.err.printin("Caught first " + e.getMessage()); } catch (IOException e) {\nSystem.err.printin("Caught second " + e.getMessage());\n}\n')),(0,o.kt)("h2",{id:"finally-block"},"Finally Block"),(0,o.kt)("p",null,"Finally block always executes irrespective of an exception being thrown or not. The final keyword allows you to create a block of code that follows a try-catch block."),(0,o.kt)("p",null,"Finally, clause is optional. It is intended to define clean-up actions which should be that executed in all conditions."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-python"},"try:\n    raise KeyboardInterrupt\nfinally:\n    print 'welcome, world!'\nOutput\nWelcome, world!\nKeyboardInterrupt\n")),(0,o.kt)("p",null,"Finally, clause is executed before try statement."),(0,o.kt)("h2",{id:"the-raise-statement"},"The Raise Statement"),(0,o.kt)("p",null,"The raise statement specifies an argument which initializes the exception object. Here, a comma follows the exception name, and argument or tuple of the argument that follows the comma."),(0,o.kt)("p",null,"Syntax:"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-python"},"raise [Exception [, args [, traceback]]]\n")),(0,o.kt)("p",null,"In this syntax, the argument is optional, and at the time of execution, the exception argument value is always none."),(0,o.kt)("h3",{id:"example-1"},"Example:"),(0,o.kt)("p",null,"A Python exception can be any value like a string, class, number, or an object. Most of these exceptions which are raised by Python core are classes with an argument which is an instance of the class."),(0,o.kt)("h2",{id:"important-python-errors"},"Important Python Errors"),(0,o.kt)("table",null,(0,o.kt)("thead",{parentName:"table"},(0,o.kt)("tr",{parentName:"thead"},(0,o.kt)("th",{parentName:"tr",align:null},"Error Type"),(0,o.kt)("th",{parentName:"tr",align:null},"Description"))),(0,o.kt)("tbody",{parentName:"table"},(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"ArithmeticError"),(0,o.kt)("td",{parentName:"tr",align:null},"ArithmeticError act as a base class for all arithmetic exceptions. It is raised for errors in arithmetic operations.")),(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"ImportError"),(0,o.kt)("td",{parentName:"tr",align:null},"ImportError is raised when you are trying to import a module which does not present. This kind of exception occurs if you have made typing mistake in the module name or the module which is not present in the standard path.")),(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"IndexError"),(0,o.kt)("td",{parentName:"tr",align:null},"An IndexErroris raised when you try to refer a sequence which is out of range.")),(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"KeyError"),(0,o.kt)("td",{parentName:"tr",align:null},"When a specific key is not found in a dictionary, a KeyError exception is raised.")),(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"NameError"),(0,o.kt)("td",{parentName:"tr",align:null},"A NameError is raised when a name is referred to in code which never exists in the local or global namespace.")),(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"ValueError"),(0,o.kt)("td",{parentName:"tr",align:null},"Value error is raised when a function or built-in operation receives an argument which may be of correct type but does not have suitable value.")),(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"EOFerror"),(0,o.kt)("td",{parentName:"tr",align:null},"This kind of error raises when one of the built-in functions (input() or raw_input()) reaches an EOF condition without reading any data.")),(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"ZeroDivisonError"),(0,o.kt)("td",{parentName:"tr",align:null},"This type of error raised when division or module by zero takes place for all numeric types.")),(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"IOError-"),(0,o.kt)("td",{parentName:"tr",align:null},"This kind of error raised when an input/output operation fails.")),(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"syntaxError"),(0,o.kt)("td",{parentName:"tr",align:null},"SyntaxErrors raised when there is an error in Python syntax.")),(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"IndentationError"),(0,o.kt)("td",{parentName:"tr",align:null},"This error raised when indentation is not properly defined")))),(0,o.kt)("h2",{id:"other-important-python-exceptions"},"Other Important Python Exceptions"),(0,o.kt)("table",null,(0,o.kt)("thead",{parentName:"table"},(0,o.kt)("tr",{parentName:"thead"},(0,o.kt)("th",{parentName:"tr",align:null},"Exception"),(0,o.kt)("th",{parentName:"tr",align:null},"Description"))),(0,o.kt)("tbody",{parentName:"table"},(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"ArithmeticException"),(0,o.kt)("td",{parentName:"tr",align:null},"Arithmetic error, such as divide-by-zero.")),(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"ArraylndexOutOfBoundsException"),(0,o.kt)("td",{parentName:"tr",align:null},"Array index is out-of-bounds.")),(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"ArrayStoreException"),(0,o.kt)("td",{parentName:"tr",align:null},"Assignment helps you to the array element of an incompatible type.")),(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"ClassCastException"),(0,o.kt)("td",{parentName:"tr",align:null},"Invalid cast")),(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"MlegalMonitorStateException"),(0,o.kt)("td",{parentName:"tr",align:null},"Illegal monitor operation, like waiting on an unlocked thread.")),(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"MlegalStateException"),(0,o.kt)("td",{parentName:"tr",align:null},"Environment or application is in wrong state.")),(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"ClassNotFoundException"),(0,o.kt)("td",{parentName:"tr",align:null},"Class not found.")),(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"CloneNotSupportedException"),(0,o.kt)("td",{parentName:"tr",align:null},"Attempt to clone an object which does not implement the Cloneable interface.")),(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"Illegal AccessException"),(0,o.kt)("td",{parentName:"tr",align:null},"Access to a class is denied.")),(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"InstantiationException"),(0,o.kt)("td",{parentName:"tr",align:null},"Occurs when you attempt to create an object of an interface or abstract class.")),(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"CloneNotSupportedException"),(0,o.kt)("td",{parentName:"tr",align:null},"Attempt to clone an object which does not implement the interface.")))),(0,o.kt)("h2",{id:"error-vs-exceptions"},"Error vs. Exceptions"),(0,o.kt)("table",null,(0,o.kt)("thead",{parentName:"table"},(0,o.kt)("tr",{parentName:"thead"},(0,o.kt)("th",{parentName:"tr",align:null},"Error"),(0,o.kt)("th",{parentName:"tr",align:null},"Exceptions"))),(0,o.kt)("tbody",{parentName:"table"},(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"All errors in Python are the unchecked type."),(0,o.kt)("td",{parentName:"tr",align:null},"Exceptions include both checked and unchecked type.")),(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"Errors occur at run time which unknown to the compiler."),(0,o.kt)("td",{parentName:"tr",align:null},"Exceptions can be recover by handling them with the help of try-catch blocks.")),(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"Errors are mostly caused by the environment in which an application is running."),(0,o.kt)("td",{parentName:"tr",align:null},"The application itself causes exceptions.")),(0,o.kt)("tr",{parentName:"tbody"},(0,o.kt)("td",{parentName:"tr",align:null},"Examples: OutofMemoryError"),(0,o.kt)("td",{parentName:"tr",align:null},"Examples: Checked Exceptions, SQL exception, NullPointerException,etc.")))),(0,o.kt)("h2",{id:"summary"},"Summary"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},"An exception is an error which happened during the execution of a program."),(0,o.kt)("li",{parentName:"ul"},"The exception indicates that, although the event can occur, this type of event happens infrequently."),(0,o.kt)("li",{parentName:"ul"},"Common Examples of Exception are 1) Division by Zero, 2) Accessing a file which is not existent, 3) Addition of two incompatible types."),(0,o.kt)("li",{parentName:"ul"},"An exception is a Python object which represents an error."),(0,o.kt)("li",{parentName:"ul"},"A try statement includes keyword try, followed by a colon (:) and a suite of code in which exceptions may occur. It has one or more clauses."),(0,o.kt)("li",{parentName:"ul"},"Catch blocks take one argument at a time, which is the type of exception that it is likely to catch."),(0,o.kt)("li",{parentName:"ul"},"The raise statement specifies an argument which initializes the exception object."),(0,o.kt)("li",{parentName:"ul"},"Finally, block always executes irrespective of an exception being thrown or not.")))}h.isMDXComponent=!0}}]);